version: '3.8'

services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - payment-service

  auth-service:
    build: ./services/auth_service
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_HOST=auth-db
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
    depends_on:
      - auth-db
      - rabbitmq

  catalog-service:
    build: ./services/catalog_service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://catalog-db:27017/catalog
    depends_on:
      - catalog-db
      - rabbitmq

  order-service:
    build: ./services/order_service
    ports:
      - "8003:8003"
    environment:
      - POSTGRES_HOST=order-db
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_password
    depends_on:
      - order-db
      - rabbitmq

  payment-service:
    build: ./services/payment_service
    ports:
      - "8004:8004"
    environment:
      - POSTGRES_HOST=payment-db
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=payment_user
      - POSTGRES_PASSWORD=payment_password
    depends_on:
      - payment-db
      - rabbitmq

  # Databases
  auth-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  catalog-db:
    image: mongo:5
    volumes:
      - catalog-db-data:/data/db

  order-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_password
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=payment_user
      - POSTGRES_PASSWORD=payment_password
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # Monitoring Stack
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus_config.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14250:14250"

volumes:
  auth-db-data:
  catalog-db-data:
  order-db-data:
  payment-db-data:
