jwt:
  secret_key: "supersecretkey"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7

oauth2:
  clients:
    - client_id: "web_app"
      client_secret: "webappsecret"
      grant_types: ["authorization_code", "refresh_token"]
      redirect_uris: ["https://app.example.com/callback"]
      scopes: ["read", "write"]
    - client_id: "mobile_app"
      client_secret: "mobileappsecret"
      grant_types: ["password", "refresh_token"]
      scopes: ["read"]

roles:
  - name: "admin"
    permissions:
      - "users:read"
      - "users:write"
      - "orders:read"
      - "orders:write"
  - name: "user"
    permissions:
      - "profile:read"
      - "profile:write"
      - "orders:read"
      - "orders:create"

rate_limiting:
  enabled: true
  requests_per_minute: 100
  burst_limit: 50

security:
  cors:
    allowed_origins: ["https://app.example.com"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["Authorization", "Content-Type"]
  https:
    enabled: true
    redirect: true
